fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.7.0"
    grafana:
      repo: "git://github.com/bfraser/puppet-grafana"
      ref: "v2.1.0"
  symlinks:
    lma_monitoring_analytics: "#{source_dir}"
